const property = [
    {
        id: 1,
        property_image: "Images/1.jpeg",
        property_name: "Palm Harbor",
        rent: 2095,
        area: "2699 Green Valley, Highland Lake",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 31, //31 days (displayed for the filter: When= "I can wait (>1month)". )
        house_type: "House",
    },
    {
        id: 2,
        property_image: "Images/2.jpeg",
        property_name: "Beverly Springfield",
        rent: 2000,
        area: "9306 Spring Terrace, Ocala",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 4,
        house_type: "House",
    },
    {
        id: 3,
        property_image: "Images/3.jpeg",
        property_name: "Faulkner Ave",
        rent: 2095,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 13,
        house_type: "House",
    },
    {
        id: 4,
        property_image: "Images/4.jpeg",
        property_name: "Palm Harbor 1",
        rent: 2095,
        area: "12603 98 North Jones St, Poughkeepsie ",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "Villa",
    },
    {
        id: 5,
        property_image: "Images/5.jpeg",
        property_name: "Beverly Springfield 1",
        rent: 2095,
        area: "13021 2 Studebaker Ave, Auburn",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 120,
        house_type: "Villa",
    },
    {
        id: 6,
        property_image: "Images/6.jpeg",
        property_name: "Faulkner Ave 1",
        rent: 2095,
        area: "2858 N Lancaster Rd, Avon Park",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "Villa",
    },
    {
        id: 7,
        property_image: "Images/7.jpeg",
        property_name: "Palm Harbor 2",
        rent: 2095,
        area: "10607 Allisheim Ave, Orlando",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 4,
        house_type: "House",
    },
    {
        id: 8,
        property_image: "Images/8.jpeg",
        property_name: "Beverly Springfield 2",
        rent: 2095,
        area: "10453 77 Woodside Drive, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 15,
        house_type: "House",
    },
    {
        id: 9,
        property_image: "Images/9.jpeg",
        property_name: "Faulkner Ave 2",
        rent: 2095,
        area: "10463 88 Bayport Road, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 10,
        house_type: "Villa",
    },
    {
        id: 10,
        property_image: "Images/10.jpeg",
        property_name: "My Home",
        rent: 2095,
        area: "946 10th Ct Sw, Vero Beach",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 21,
        house_type: "House",
    },
    {
        id: 11,
        property_image: "Images/10.jpeg",
        property_name: "Faulkner Ave 3",
        rent: 2000,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 24,
        house_type: "House",
    },
    {
        id: 12,
        property_image: "Images/4.jpeg",
        property_name: "Beverly Springfield 3",
        rent: 1500,
        area: "10453 77 Woodside Drive, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 18,
        house_type: "House",
    },
    {
        id: 13,
        property_image: "Images/1.jpeg",
        property_name: "My Home 2",
        rent: 2500,
        area: "946 10th Ct Sw, Vero Beach",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 21,
        house_type: "House",
    },
    {
        id: 14,
        property_image: "Images/5.jpeg",
        property_name: "My Home 3",
        rent: 2500,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 40,
        house_type: "House",
    },
    {
        id: 15,
        property_image: "Images/6.jpeg",
        property_name: "My Home 4",
        rent: 800,
        area: "10463 88 Bayport Road, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 45,
        house_type: "House",
    },
    {
        id: 16,
        property_image: "Images/3.jpeg",
        property_name: "Faulkner Ave 4",
        rent: 3000,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 32,
        house_type: "House",
    },
    {
        id: 17,
        property_image: "Images/10.jpeg",
        property_name: "Faulkner Ave 4",
        rent: 4000,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 24,
        house_type: "House",
    },
    {
        id: 18,
        property_image: "Images/1.jpeg",
        property_name: "My Home 2",
        rent: 2600,
        area: "946 10th Ct Sw, Vero Beach",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "Villa",
    },
    {
        id: 19,
        property_image: "Images/8.jpeg",
        property_name: "Beverly Springfield 5",
        rent: 2700,
        area: "10453 77 Woodside Drive, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 17,
        house_type: "Villa",
    },
    {
        id: 20,
        property_image: "Images/7.jpeg",
        property_name: "Beverly Springfield 6",
        rent: 2700,
        area: "10453 77 Woodside Drive, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 45,
        house_type: "Villa",
    },
    {
        id: 21,
        property_image: "Images/6.jpeg",
        property_name: "Faulkner Ave 5",
        rent: 5000,
        area: "2858 N Lancaster Rd, Avon Park",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "House",
    },
    {
        id: 22,
        property_image: "Images/8.jpeg",
        property_name: "Beverly Springfield 8",
        rent: 2700,
        area: "10453 77 Woodside Drive, Bronx",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 17,
        house_type: "House",
    },
    {
        id: 23,
        property_image: "Images/1.jpeg",
        property_name: "Palm Harbor",
        rent: 3000,
        area: "2699 Green Valley, Highland Lake",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0, 
        house_type: "Villa",
    },
    {
        id: 24,
        property_image: "Images/2.jpeg",
        property_name: "Beverly Springfield",
        rent: 3500,
        area: "9306 Spring Terrace, Ocala",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 20,
        house_type: "Villa",
    },
    {
        id: 25,
        property_image: "Images/3.jpeg",
        property_name: "Faulkner Ave",
        rent: 10000,
        area: "11368 28 South Road, Corona",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 35,
        house_type: "Villa",
    },
]

export default property;