const property = [
    {
        id: 1,
        property_image: "Images/1.jpeg",
        property_name: "Palm Harbor",
        rent: 2095,
        area: "2699 Green Valley, Highland Lake",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 31, //31 days
        house_type: "House",
    },
    {
        id: 2,
        property_image: "Images/2.jpeg",
        property_name: "Beverly Springfield",
        rent: 2095,
        area: "9306 Spring Terrace, Ocala",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 4,
        house_type: "House",
    },
    {
        id: 3,
        property_image: "Images/3.jpeg",
        property_name: "Faulkner Ave",
        rent: 2095,
        area: "11368 28 South Road, Corona",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 13,
        house_type: "House",
    },
    {
        id: 4,
        property_image: "Images/4.jpeg",
        property_name: "Palm Harbor 1",
        rent: 2095,
        area: "12603 98 North Jones St, Poughkeepsie ",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "Villa",
    },
    {
        id: 5,
        property_image: "Images/5.jpeg",
        property_name: "Beverly Springfield 1",
        rent: 2095,
        area: "13021 2 Studebaker Ave, Auburn",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 120,
        house_type: "Villa",
    },
    {
        id: 6,
        property_image: "Images/6.jpeg",
        property_name: "Faulkner Ave 1",
        rent: 2095,
        area: "2858 N Lancaster Rd, Avon Park",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 0,
        house_type: "Villa",
    },
    {
        id: 7,
        property_image: "Images/7.jpeg",
        property_name: "Palm Harbor 2",
        rent: 2095,
        area: "10607 Allisheim Ave, Orlando",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 4,
        house_type: "House",
    },
    {
        id: 8,
        property_image: "Images/8.jpeg",
        property_name: "Beverly Springfield 2",
        rent: 2095,
        area: "10453 77 Woodside Drive, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 15,
        house_type: "House",
    },
    {
        id: 9,
        property_image: "Images/9.jpeg",
        property_name: "Faulkner Ave 2",
        rent: 2095,
        area: "10463 88 Bayport Road, Bronx",
        state: "NY",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 10,
        house_type: "Villa",
    },
    {
        id: 10,
        property_image: "Images/10.jpeg",
        property_name: "My Home",
        rent: 2095,
        area: "946 10th Ct Sw, Vero Beach",
        state: "FL",
        bedrooms: 3,
        bathrooms: 2,
        dimensions: [5, 7],
        move_in: 4,
        house_type: "House",
    },
]

export default property;